

_rotta:
    path:     /gelaterie
    defaults: { _controller: FrontBundle:Gelateria:rotta }

_gelateria:
    path:     /gelateria/{id}
    defaults: { _controller: FrontBundle:Gelateria:gelateria }

_segnalagelateria:
    path:     /segnalagelateria
    defaults: { _controller: FrontBundle:Gelateria:segnalagelateria }

_editgelateria:
    path:     /gelateria/{id}/edit
    defaults: { _controller: FrontBundle:Gelateria:edit }

_creategelateria:
    path:     /newgelateria
    defaults: { _controller: FrontBundle:Gelateria:create }

_home:
    path:     /
    defaults: { _controller: FrontBundle:Home:Home }
    
_comefunziona:
    path:     /comefunziona
    defaults: { _controller: FrontBundle:Home:Comefunziona }

_search:
    path:     /search
    defaults: { _controller: FrontBundle:Search:Search }

_userlogin:
    path:     /Userlogin
    defaults: { _controller: FrontBundle:User:Userlogin}

_userregistrati:
    path:     /Userregistrati
    defaults: { _controller: FrontBundle:User:Userregistrati}

_userpswdimenticata:
    path:     /Userpswdimenticata
    defaults: { _controller: FrontBundle:User:Userpswdimenticata}

_userimpostazioniutente:
    path:     /Userimpostazioniutente
    defaults: { _controller: FrontBundle:User:Userimpostazioniutente}
