<?php

namespace FrontBundle\Repository;

/**
 * ListaGustiRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ListaGustiRepository extends \Doctrine\ORM\EntityRepository
{
}
