<?php

namespace FrontBundle\Repository;

/**
 * SegnalazioneGelateriaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SegnalazioneGelateriaRepository extends \Doctrine\ORM\EntityRepository
{
}